# Generated by Django 5.0.3 on 2024-03-24 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('coordinator', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('schoolId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='school_app.school')),
            ],
        ),
    ]
