# Generated by Django 5.0.3 on 2024-03-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='schoolId',
            new_name='school',
        ),
    ]
