# Generated by Django 4.2.11 on 2024-03-28 04:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0002_rename_schoolid_course_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coordinator',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
