# Generated by Django 4.2.11 on 2024-03-28 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='head_of_school',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
